# Manzoi Death Message v1.0.0
# @author     ucchy
# @license    GPLv3
# @copyright  Copyright ucchy 2013

# Output to server.log
loggingDeathMessage: true

# Suppress death message exclude OPs.
suppressDeathMessage: true
