#case: String
#%p Player, %k Killer, %o Owner, %i Item
arrow: arrow(%p_%k_%i_%o)
bat: bat(%p_%k_%i_%o)
blaze: blaze(%p_%k_%i_%o)
cave_spider: cave_spider(%p_%k_%i_%o)
contact: contact(%p_%k_%i_%o)
creeper: creeper(%p_%k_%i_%o)
custom: custom(%p_%k_%i_%o)
default: default(%p_%k_%i_%o)
dispenser: dispenser(%p_%k_%i_%o)
drowning: drowning(%p_%k_%i_%o)
ender_dragon: ender_dragon(%p_%k_%i_%o)
enderman: enderman(%p_%k_%i_%o)
fall: fall(%p_%k_%i_%o)
falling: falling(%p_%k_%i_%o)
fire: fire(%p_%k_%i_%o)
ghast: ghast(%p_%k_%i_%o)
giant: giant(%p_%k_%i_%o)
iron_golem: iron_golem(%p_%k_%i_%o)
lava: lava(%p_%k_%i_%o)
lightning: lightning(%p_%k_%i_%o)
magic: magic(%p_%k_%i_%o)
magma_cube: magma_cube(%p_%k_%i_%o)
pig_zombie: pig_zombie(%p_%k_%i_%o)
poison: poison(%p_%k_%i_%o)
potion: potion(%p_%k_%i_%o)
pvp: pvp(%p_%k_%i_%o)
showman: showman(%p_%k_%i_%o)
silverfish: silverfish(%p_%k_%i_%o)
skeleton: skeleton(%p_%k_%i_%o)
slime: slime(%p_%k_%i_%o)
snowball: snowball(%p_%k_%i_%o)
spider: spider(%p_%k_%i_%o)
starvation: starvation(%p_%k_%i_%o)
starving: starving(%p_%k_%i_%o)
suffocation: suffocation(%p_%k_%i_%o)
suicide: suicide(%p_%k_%i_%o)
tamewolf: tamewolf(%p_%k_%i_%o)
throw: throw(%p_%k_%i_%o)
tnt: tnt(%p_%k_%i_%o)
unknown: unknown(%p_%k_%i_%o)
void: void(%p_%k_%i_%o)
wither: wither(%p_%k_%i_%o)
wolf: wolf(%p_%k_%i_%o)
zombie: zombie(%p_%k_%i_%o)
zombiepig: zombiepig(%p_%k_%i_%o)
